package cn.sinjinsong.eshop.common.domain.entity.message;

import cn.sinjinsong.eshop.common.enumeration.message.MessageStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ConsumerTransactionMessageDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer_transaction_message.msgId
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer_transaction_message.create_time
     *
     * @mbggenerated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer_transaction_message.topic
     *
     * @mbggenerated
     */
    private String topic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer_transaction_message.message_status
     *
     * @mbggenerated
     */
    private MessageStatus messageStatus;
}