package cn.sinjinsong.eshop.common.domain.entity.message;

import cn.sinjinsong.eshop.common.enumeration.message.MessageStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ProducerTransactionMessageDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producer_transaction_message.msgId
     *
     * @mbggenerated
     */
    private Long id;
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producer_transaction_message.message_status
     *
     * @mbggenerated
     */
    private MessageStatus messageStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producer_transaction_message.update_time
     *
     * @mbggenerated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producer_transaction_message.create_time
     *
     * @mbggenerated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producer_transaction_message.send_times
     *
     * @mbggenerated
     */
    private Integer sendTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producer_transaction_message.topic
     *
     * @mbggenerated
     */
    private String topic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producer_transaction_message.body
     *
     * @mbggenerated
     */
    private byte[] body;

}