package cn.sinjinsong.eshop.dao.order;

import cn.sinjinsong.eshop.common.domain.dto.order.OrderQueryConditionDTO;
import cn.sinjinsong.eshop.common.domain.entity.order.OrderDO;
import com.github.pagehelper.Page;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface OrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    int insert(OrderDO record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    OrderDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderDO record);

   

    Page<OrderDO> findAll(@Param("pageNum") Integer pageNum, @Param("pageSize") Integer pageSize);
    Page<OrderDO> findByCondition(@Param("condition") OrderQueryConditionDTO condition, @Param("pageNum") Integer pageNum, @Param("pageSize") Integer pageSize);
}