package cn.sinjinsong.eshop.dao.message;

import cn.sinjinsong.eshop.common.domain.entity.message.ConsumerTransactionMessageDO;
import cn.sinjinsong.eshop.common.enumeration.message.MessageStatus;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ConsumerTransactionMessageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_transaction_message
     *
     * @mbggenerated
     */
    int insert(ConsumerTransactionMessageDO record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_transaction_message
     *
     * @mbggenerated
     */
    ConsumerTransactionMessageDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_transaction_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConsumerTransactionMessageDO record);

    MessageStatus findStatusById(Long id);
}