package cn.sinjinsong.eshop.common.domain.entity.mail;

import cn.sinjinsong.eshop.common.domain.entity.user.UserDO;
import cn.sinjinsong.eshop.common.enumeration.mail.MailStatus;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class MailDO implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.id
     *
     * @mbggenerated
     */
    private Long id;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.sender
     *
     * @mbggenerated
     */
    private UserDO sender;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.receiver
     *
     * @mbggenerated
     */
    private UserDO receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.mail_status
     *
     * @mbggenerated
     */
    private MailStatus mailStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.text
     *
     * @mbggenerated
     */
    private MailTextDO text;
}